### ISSUE TITLE
Exceptions thrown in the "except" block hide the previous exceptions

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/ckanext-datapackager#66]
On:

https://github.com/frictionlessdata/ckanext-datapackager/blob/cce2316b419ad2be0c9a489051b2d09ae414a7ca/ckanext/datapackager/logic/action/create.py#L66:L71

If an exception is raised by `package_delete` inside the `except` block, we miss the previous exception thrown. This makes things harder to debug. We need to find a way to raise both exceptions if needed, possibly chaining them with `raise from`.

**Comment by vitorbaptista** [comment]
I found a good way to handle this:

```python
try:
    raise Exception('first exception')
except Exception as e:
    try:
        raise Exception('second exception')
    except Exception as e2:
        raise e2 from e
    else:
        raise e
```

Running this code gets us:
```
Traceback (most recent call last):
  File "foobar.py", line 2, in <module>
    raise Exception('first exception')
Exception: first exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "foobar.py", line 7, in <module>
    raise e2 from e
  File "foobar.py", line 5, in <module>
    raise Exception('second exception')
Exception: second exception
```

So we keep both exceptions. If the second exception wasn't raised, it'll run the `else` block which simply raises the original exception, so we handle all cases. The `raise from` construct is Python3-only, but six has `six.raise_from()` to handle this in a Python2-compatible way.
